### PR TITLE
Fix error in PregMatchTypeSpecifyingExtension

### PR DESCRIPTION
**Pull request by staabm**
should fix a crash in when running on the composer project, as discussed in https://github.com/composer/pcre/pull/27#issuecomment-2223089169

### CODE REVIEW

**Comment by staabm** [comment]
btw: I just saw errors in composer repo beeing reported in 

https://github.com/composer/composer/blob/07aee7ea8e1ab691c14bfe4258f826a8aae95ed3/src/Composer/Util/Git.php#L408

comparisons are a known problem: https://github.com/phpstan/phpstan/issues/11293

**Comment by staabm** [comment]
turn `if (Preg::match('{^\s*HEAD branch:\s(.+)\s*$}m', $line, $matches) > 0) {` into `if (Preg::isMatch('{^\s*HEAD branch:\s(.+)\s*$}m', $line, $matches)) {` and it should work

**Comment by Seldaek** [comment]
Thanks, this is awesome already :)

And with phpstan 1.11.x-dev gets even better. As a frequent regex user I absolutely love this :D 

Yeah a few places weren't migrated to isMatch but they really ought to IMO.

I've checked and indeed it seems like with all fixes in, isMatchStrictGroups isn't really needed anymore.. However I kinda like it as it still does runtime enforcement, but what I think would be even cooler is if we can detect with PHPStan that the regex contains optional groups.. and error because isMatchStrictGroups is not safe and might throw.

**Comment by staabm** [comment]
> but what I think would be even cooler is if we can detect with PHPStan that the regex contains optional groups.. and error because isMatchStrictGroups is not safe and might throw.

the array-shape-matcher already detects optional groups.

if you can bring up examples of what you want todo I can look into it

**Comment by Seldaek** [comment]
Yeah I realize it does it already, that's why I think it might be fairly simple to detect when strict-group functions have a shape that has nullable groups, then it'll possibly throw, and the regex needs adjusting. I'll open a PR with tests.

**Pull request merged**
